import { useEffect, useState } from 'react'
import { fetchIrrigationPrediction } from '../api'

export default function Tips() {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchIrrigationPrediction()
      .then(setData)
      .catch(() => setData(null))
      .finally(() => setLoading(false))
  }, [])

  if (loading) return (
    <div className="loading-wrap">
      <div className="loading-spinner" />
      <div style={{ color: 'var(--text-muted)', fontSize: 13 }}>Loading recommendations…</div>
    </div>
  )

  const tips = buildTips(data)

  return (
    <div>
      <div className="section-title">Recommendations</div>

      <div className="banner normal" style={{ marginBottom: 16 }}>
        <span className="banner-title">💡 AI-Powered Insights</span>
        <span className="banner-body">
          Recommendations generated by analysing sensor readings and historical moisture trends from your field.
        </span>
      </div>

      {tips.map((tip, i) => <TipCard key={i} tip={tip} />)}

      <p style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 16, textAlign: 'center', lineHeight: 1.6 }}>
        These are predictive recommendations based on current data.{'\n'}Always apply local agronomic judgment.
      </p>
    </div>
  )
}

function buildTips(data) {
  const h = data?.irrigate_in_hours ?? null

  const tips = []

  if (h === null) {
    tips.push({
      priority: 'LOW', icon: '✅',
      title: 'All Conditions Normal',
      body: 'No specific actions needed. Continue monitoring soil moisture levels regularly.',
    })
  } else if (h === 0) {
    tips.push({
      priority: 'HIGH', icon: '🚨',
      title: 'Irrigate Immediately',
      body: 'Soil moisture has reached a critical level. Start irrigation now to prevent crop stress and potential yield loss.',
    })
  } else if (h < 2) {
    tips.push({
      priority: 'HIGH', icon: '💧',
      title: 'Irrigate Very Soon',
      body: `Soil moisture will drop to critical levels in approximately ${h} hour(s). Begin irrigation within the next hour.`,
    })
  } else if (h < 8) {
    tips.push({
      priority: 'MEDIUM', icon: '💧',
      title: 'Schedule Irrigation',
      body: `Next irrigation recommended in ~${h} hours. Best window: early morning (6–8 AM) or evening (5–7 PM) to minimise evaporation loss.`,
    })
  } else {
    tips.push({
      priority: 'LOW', icon: '✅',
      title: 'Moisture Levels Healthy',
      body: `Soil moisture is adequate. Next irrigation is not needed for approximately ${h} hours. Continue monitoring.`,
    })
  }

  // Always include best practice
  tips.push({
    priority: 'LOW', icon: '🌅',
    title: 'Best Irrigation Time',
    body: 'Irrigate during early morning (6–8 AM) or late evening (5–7 PM) to reduce evaporation by up to 30% and ensure deeper soil penetration.',
  })

  // Model improvement hint
  if (data?.source === 'rule_based_fallback' && data?.note) {
    tips.push({
      priority: 'LOW', icon: '🤖',
      title: 'Improve AI Accuracy',
      body: data.note,
    })
  }

  return tips
}

function TipCard({ tip }) {
  const cls = tip.priority === 'HIGH' ? 'critical' : tip.priority === 'MEDIUM' ? 'warning' : 'normal'
  const bg = tip.priority === 'HIGH' ? 'var(--critical-bg)' : tip.priority === 'MEDIUM' ? 'var(--warning-bg)' : '#fff'
  return (
    <div className="card" style={{ marginBottom: 10, background: bg }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 9 }}>
          <span style={{ fontSize: 26 }}>{tip.icon}</span>
          <span style={{ fontWeight: 700, fontSize: 14 }}>{tip.title}</span>
        </div>
        <span className={`badge ${cls}`}>{tip.priority}</span>
      </div>
      <p style={{ fontSize: 13, color: 'var(--text-primary)', lineHeight: 1.65, paddingLeft: 35 }}>
        {tip.body}
      </p>
    </div>
  )
}