import { useEffect, useState } from 'react'
import {
  fetchIrrigationPrediction,
  fetchNPKRecommendation,
  fetchPHCorrection,
  fetchStressPrediction,
} from '../api'

export default function Tips() {
  const [data,    setData]    = useState({})
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    Promise.allSettled([
      fetchIrrigationPrediction(),
      fetchNPKRecommendation(),
      fetchPHCorrection(),
      fetchStressPrediction(),
    ]).then(([irr, npk, ph, stress]) => {
      setData({
        irrigation: irr.status === 'fulfilled' ? irr.value : null,
        npk:        npk.status === 'fulfilled' ? npk.value : null,
        ph:         ph.status  === 'fulfilled' ? ph.value  : null,
        stress:     stress.status === 'fulfilled' ? stress.value : null,
      })
    }).finally(() => setLoading(false))
  }, [])

  if (loading) return <p className="loading">Loading AI recommendations…</p>

  const tips = buildTips(data)

  return (
    <div>
      <div className="section-title">Recommendations</div>
      <div className="banner normal" style={{ marginBottom: 16 }}>
        <span className="banner-title">💡 Smart Insights</span>
        <span className="banner-body">
          These recommendations are generated by analysing sensor data, historical patterns,
          and crop growth stage models.
        </span>
      </div>

      {tips.map((tip, i) => <TipCard key={i} tip={tip} />)}

      <p style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 12, textAlign: 'center' }}>
        Note: These are predictive recommendations, not urgent alerts.
      </p>
    </div>
  )
}

function buildTips(data) {
  const tips = []

  if (data.irrigation) {
    const h = data.irrigation.irrigate_in_hours
    tips.push({
      priority: h < 2 ? 'HIGH' : h < 6 ? 'MEDIUM' : 'LOW',
      icon: '💧', title: 'Optimal Irrigation Time',
      body: h <= 0
        ? 'Irrigate immediately — soil moisture is critically low.'
        : `Next irrigation recommended in ~${h} hours. Best time: early morning (6–8 AM) or evening (5–7 PM).`,
    })
  }

  if (data.npk) {
    const recs = data.npk.recommendations || (data.npk.recommendation ? [data.npk.recommendation] : [])
    recs.forEach(r => tips.push({ priority: 'HIGH', icon: '🌱', title: 'Fertilizer Application', body: r }))
  }

  if (data.ph?.amendment) {
    tips.push({
      priority: 'MEDIUM', icon: '🧪', title: 'Soil pH Correction',
      body: data.ph.amendment,
    })
  } else if (data.ph?.message && !data.ph.message.includes('No correction')) {
    tips.push({ priority: 'LOW', icon: '🧪', title: 'Soil pH Status', body: data.ph.message })
  }

  if (data.stress?.recommendations) {
    data.stress.recommendations.forEach(r =>
      tips.push({ priority: data.stress.risk_level === 'high' ? 'HIGH' : 'MEDIUM', icon: '🌡️', title: 'Crop Stress Advice', body: r })
    )
  }

  return tips.length ? tips : [{ priority: 'LOW', icon: '✅', title: 'All conditions nominal', body: 'No specific actions needed. Continue current practices.' }]
}

function TipCard({ tip }) {
  const cls = tip.priority === 'HIGH' ? 'critical' : tip.priority === 'MEDIUM' ? 'warning' : 'normal'
  return (
    <div className="card" style={{ marginBottom: 10 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 6 }}>
        <span style={{ fontWeight: 700 }}>{tip.icon} {tip.title}</span>
        <span className={`badge ${cls}`}>{tip.priority}</span>
      </div>
      <p style={{ fontSize: 13, color: 'var(--text-primary)', lineHeight: 1.5 }}>{tip.body}</p>
    </div>
  )
}
